name: Build bundle
on:
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  bundle:
    name: ${{ matrix.platform.os }}/${{ matrix.platform.arch }}
    runs-on: ${{ matrix.platform.label }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: linux
            arch: amd64
            label: ubuntu-24.04
          - os: linux
            arch: arm64
            label: ubuntu-24.04-arm
          - os: windows
            arch: amd64
            label: windows-2025
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
      - name: Prepare .env
        run: |
          if [[ -n $ENVFILE ]]; then
            echo "$ENVFILE" > .env
          else
            cp .env{.example,}
          fi
          echo "GATSBY_REPOSITORY_NAME=${{ github.repository }}" >> .env
          echo "GATSBY_REPOSITORY_URL=${{ github.server_url }}/${{ github.repository }}/tree/${{ github.sha }}" >> .env
        env:
          ENVFILE: ${{ secrets.ENVFILE }}
      - name: Install corepack
        run: |
          npm install -g -f corepack
          corepack enable
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: |
          yarn build
